name: Release collection Galaxy
description: This releases collection on Galaxy
author: Sagar Paul
inputs:
  ansible_galaxy_api_key: # string
    description: "The Galaxy API key"
    required: true
runs:
  using: composite
  steps:
    - name: "Checkout operation"
      uses: actions/checkout@v4

    - name: "Build the collection"
      shell: bash
      run: |
        ansible-galaxy collection build -v --force

    - name: "Publish the collection on Galaxy"
      shell: bash
      run: |
        [[ "${{ inputs.ansible_galaxy_api_key != '' }}" ]] || { echo "ansible_galaxy_api_key is required to publish on galaxy" ; exit 1; }
        TARBALL=$(ls -1 ./*.tar.gz)
      # ansible-galaxy collection publish "${TARBALL}" --api-key "${{ inputs.ansible_galaxy_api_key }}"
