---
name: ansible-content-action
description: This is a monolythic action for Ansible contnet testing
author: Sagar Paul

runs:
  using: composite
  steps:
    # run ansible-lint
    - name: Run ansible-lint
      if: ${{ github.job == 'ansible-lint' }}
      uses: KB-perByte/ansible-content-action/.github/actions/ansible-lint@main

    # run sanity with declared matrix
    - name: Run sanity
      if: ${{ github.job == 'sanity' }}
      uses: KB-perByte/ansible-content-action/.github/actions/sanity@main

    # run sanity with declared matrix
    - name: Release Galaxy"
      if: ${{ github.event == 'published' }}
      uses: KB-perByte/ansible-content-action/.github/actions/ansible-galaxy@main
