---
name: Test_collection_mono
description: Test conditional monolithic collection.

inputs:
  path:
    description: |
      Path to the collection to validate changelog from.
    required: false
    default: "."
  base_ref:
    description: The pull request base ref.
    required: false
    default: ${{ github.event.pull_request.base.ref }}

runs:
  steps:
    - name: Test collection
      uses: KB-perByte/hold_gha/.github/actions/test_collection/action.yml@main
