---
name: ansible-content-actions
description: This is a monolithic action for Ansible contnet testing
author: Ansible Devtools Team
branding:
  icon: play
  color: red
inputs:
  path:
    description: |
      Path to the collection to add tox-ansible.ini file.
  base_ref:
    description: The pull requests base.
  repo:
    description: Repository url
  environment:
    description: The deployment environment
  ah_publish:
    description: Publish the collection on automation hub
  galaxy_publish:
    description: Publish the collection on galaxy
  collection_pre_install:
    description: Publish the collection on galaxy
runs:
  using: composite
