---
name: ansible-content-action
description: This is a monolythic action for Ansible contnet testing
author: Sagar Paul
inputs:
  # lint
  path:
    description: >
      Specific path to lint instead of the default `.`. Multiple arguments are
      not supported and you will need to alter linter configuration to
      accommodate other use cases.
    required: false
    # That default is just a placeholder workaround for no arguments use-case
    # Feeding "." or empty string to ansible-lint makes it believe it is a role
    default: --show-relpath
  args:
    description: deprecated
    deprecationMessage: >
      Arbitrary args are no longer accepted, please use path instead and
      linter own configuration file to change its behavior.
    required: false
    default: ""
  # # sanity
  # collection_pre_install:
  #   required: false
  #   type: string
  #   default: ""
  # matrix_exclude:
  #   # https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix
  #   # 2.9 supports Python 3.5-3.8
  #   # 2.13 supports Python 3.8-3.10
  #   # 2.14 supports Python 3.9-3.11
  #   # 2.15 supports Python 3.9-3.11
  #   # 2.16 supports Python 3.10-3.11
  #   # https://docs.ansible.com/ansible/devel/roadmap/ROADMAP_2_16.html
  #   # milestone is 2.16 until after 2.16 branches from devel
  #   # devel is 2.16 until 2023-09-18
  #   default: >-
  #     [
  #       {
  #         "ansible-version": "stable-2.9",
  #         "python-version": "3.9"
  #       },
  #       {
  #         "ansible-version": "stable-2.9",
  #         "python-version": "3.10"
  #       },
  #       {
  #         "ansible-version": "stable-2.9",
  #         "python-version": "3.11"
  #       },
  #       {
  #         "ansible-version": "stable-2.13",
  #         "python-version": "3.7"
  #       },
  #       {
  #         "ansible-version": "stable-2.13",
  #         "python-version": "3.11"
  #       },
  #       {
  #         "ansible-version": "stable-2.14",
  #         "python-version": "3.7"
  #       },
  #       {
  #         "ansible-version": "stable-2.14",
  #         "python-version": "3.8"
  #       },
  #       {
  #         "ansible-version": "stable-2.15",
  #         "python-version": "3.7"
  #       },
  #       {
  #         "ansible-version": "stable-2.15",
  #         "python-version": "3.8"
  #       },
  #       {
  #         "ansible-version": "milestone",
  #         "python-version": "3.7"
  #       },
  #       {
  #         "ansible-version": "milestone",
  #         "python-version": "3.8"
  #       },
  #       {
  #         "ansible-version": "milestone",
  #         "python-version": "3.9"
  #       },
  #       {
  #         "ansible-version": "devel",
  #         "python-version": "3.7"
  #       },
  #       {
  #         "ansible-version": "devel",
  #         "python-version": "3.8"
  #       },
  #       {
  #         "ansible-version": "devel",
  #         "python-version": "3.9"
  #       }
  #     ]
  #   required: false
  #   type: string
  # matrix_include:
  #   # python 3.6 is not available after ubuntu-20.04
  #   # python 3.6 is not supported on ansible 2.12+
  #   default: >-
  #     [
  #       {
  #         "os": "ubuntu-20.04",
  #         "ansible-version": "stable-2.9",
  #         "python-version": "3.6"
  #       },
  #     ]
  #   required: false
  #   type: string
  # unstable:
  #   default: >-
  #     [
  #       "devel",
  #     ]
  #   required: false
  #   type: string

runs:
  using: composite
  steps:
    # initial setup
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    # run ansible-lint
    - name: Install Ansible and dependencies
      shell: bash
      if: ${{ github.job == 'ansible-lint' }}
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint

    - name: Run Ansible-lint
      if: ${{ github.job == 'ansible-lint' }}
      shell: bash
      run: ansible-lint

    # run sanity with declared matrix
    - name: Run sanity
      if: ${{ github.job == 'sanity' }}
      uses: KB-perByte/ansible-content-action/.github/actions/sanity@main
