---
name: ansible-github-actions
description: This is a monolithic action for Ansible contnet testing
author: Sagar Paul
inputs:
  ansible_galaxy_api_key: # string
    description: "The Galaxy api key"
    required: false
  gh_token: # string
    description: "The GH token"
    required: false
runs:
  using: composite
