---
name: ansible-content-action
description: This is a monolythic action for Ansible contnet testing
author: Sagar Paul
inputs:
  path:
    description: >
      Specific path to lint instead of the default `.`. Multiple arguments are
      not supported and you will need to alter linter configuration to
      accommodate other use cases.
    required: false
    # That default is just a placeholder workaround for no arguments use-case
    # Feeding "." or empty string to ansible-lint makes it believe it is a role
    default: --show-relpath
  args:
    description: deprecated
    deprecationMessage: >
      Arbitrary args are no longer accepted, please use path instead and
      linter own configuration file to change its behavior.
    required: false
    default: ""
runs:
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Ansible and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint

    - name: Run Ansible-lint
      run: ansible-lint
