---
name: Ansible lint test job
description: This ansible-lint workflow
author: Sagar Paul

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install ansible-lint and dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint

    - name: Run Ansible-lint
      shell: bash
      run: ansible-lint
