name: Release collection Automation Hub
description: This releases collection on Automation Hub
author: Sagar Paul
inputs:
  ah_token: # string
    description: "The Automation Hub API key"
    required: true
runs:
  using: composite
  steps:
    - name: "Checkout operation"
      uses: actions/checkout@v4

    - name: "Build the collection"
      shell: bash
      run: |
        ansible-galaxy collection build -v --force

    - name: "Publish the collection on Automation Hub"
      shell: bash
      run: |
        [[ "${{ inputs.ah_token != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 1; }
        TARBALL=$(ls -1 ./*.tar.gz)
        cat << EOF > ansible.cfg
        [galaxy]
        server_list = rh_automation_hub
        [galaxy_server.rh_automation_hub]
        url=https://cloud.redhat.com/api/automation-hub/
        auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
        token=${{ inputs.ah_token }}
        EOF
      # ansible-galaxy collection publish "${TARBALL}"
      # rm ansible.cfg
