---
name: generate-tox-ansible-matrix
description: Generate a tox ansible matrix for the given scope.

inputs:
  scope:
    description: Scope to generate matrix for.
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: "${{github.event.pull_request.head.ref}}"
        repository: "${{ github.event.pull_request.head.repo.full_name }}"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: "Check for tox-ansible.ini file, else add default"
      uses: ansible/ansible-content-actions/.github/actions/add_tox_ansible@main

    - name: "Install tox-ansible, includes tox"
      run: "python -m pip install git+https://github.com/ansible/tox-ansible.git"

    - name: Generate matrix
      id: generate-matrix
      run: >
        python -m tox --ansible --gh-matrix --matrix-scope ${{ inputs.scope }} --conf
        tox-ansible.ini
  outputs:
    envlist: "${{ steps.generate-matrix.outputs.envlist }}"
