---
name: generate-tox-ansible-matrix
description: Generate a tox ansible matrix for the given scope.

inputs:
  scope:
    description: Scope to generate matrix for.
    required: true

outputs:
  name:
    description: "The generated tox env list."
    value: ${{ steps.generate-matrix.outputs.envlist }}"

runs:
  using: composite
  steps:
    - name: Fail early if no scope was provided for matrix generation
      if: ${{ inputs.scope }} == ""
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('A scope needs to be provided to generate matrix.')

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: "${{github.event.pull_request.head.ref}}"
        repository: "${{ github.event.pull_request.head.repo.full_name }}"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: "Check for tox-ansible.ini file, else add default"
      run: >-
        [ -e tox-ansible.ini ] || { echo "[ansible]" > tox-ansible.ini && echo
        -e "skip =\n\tpy3.7\n\tpy3.8\n\t2.9\n\t2.10\n\t2.11\n\t2.12\n\t2.13" >>
        tox-ansible.ini; }
      shell: bash

    - name: "Install tox-ansible, includes tox"
      shell: bash
      run: "python -m pip install git+https://github.com/ansible/tox-ansible.git"

    - name: Generate matrix
      id: generate-matrix
      shell: bash
      run: >
        echo "envlist=$(python -m tox --ansible --gh-matrix --matrix-scope ${{ inputs.scope }} --conf tox-ansible.ini)" >> $GITHUB_OUTPUT
