---
name: run-unit-tests
description: Run unit tests with tox-ansible.

inputs:
  matrix-entry:
    description: |
      A dictionary containing matrix information to run the unit tests against.
      Example, "{"description": "Unit tests using ansible-core 2.14 and python 3.9", "factors": ["unit", "py3.9", "2.14"], "name": "unit-py3.9-2.14", "python": "3.9"}"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.matrix-entry.python }}"

    - name: "Install tox-ansible, includes tox"
      run: python -m pip install tox-ansible

    - name: "Check for tox-ansible.ini file, else add default"
      uses: ansible/ansible-content-actions/.github/actions/add_tox_ansible@main

    # TO-DO: remove this when cp312 wheels are ready for ansible-pylibssh
    - name: Install build toolchain and openssl headers on Linux
      shell: bash
      run: sudo apt update && sudo apt install build-essential libssl-dev libssh-dev
      if: ${{ inputs.matrix-entry.python == 3.12 }}

    - name: Run tox unit tests
      run: >-
        python -m tox --ansible -e ${{ inputs.matrix-entry.name }} --conf
        tox-ansible.ini
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
