---
name: run-unit-tests
description: Run unit tests with tox-ansible.

inputs:
  matrix-python:
    description: The python version for running unit test.
    required: true
  matrix-name:
    description: |
      The python x ansible version for running the unit test.
      This should be in the format unit-pyX.Y-ansible_version
      Example, "unit-py3.9-2.14".
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: "${{ github.event.pull_request.head.sha }}"
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "${{ inputs.matrix-python }}"

    - name: "Install tox-ansible, includes tox"
      shell: bash
      run: python -m pip install tox-ansible

    # TO-DO: remove this when cp312 wheels are ready for ansible-pylibssh
    - name: Install build toolchain and openssl headers on Linux
      shell: bash
      run: sudo apt update && sudo apt install build-essential libssl-dev libssh-dev
      if: ('py3.12', ${{ inputs.matrix-python }})

    - name: Run tox unit tests
      shell: bash
      run: >-
        python -m tox --ansible -e ${{ inputs.matrix-name }}
