name: Changelog required
on: # yamllint disable-line rule:truthy
  workflow_call:
jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Require a changelog
    if: "!contains(github.event.pull_request.labels.*.name, 'skip-changelog')"
    steps:
      - name: Checkout the collection repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: "0"

      - name: Validate changelog
        uses: KB-perByte/hold_gha/.github/actions/ansible_validate_changelog@main
