---
name: Lint
"on":
  pull_request:
    branches:
      - main
      - stable
      - release/v*
  workflow_call: null
jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install ansible-lint and dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint
      - name: Run Ansible-lint
        shell: bash
        run: ansible-lint
